# Generated by Django 6.0.5 on 2026-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время запроса')),
                ('http_method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('url_path', models.CharField(max_length=2048, verbose_name='Путь запроса')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Код ответа')),
                ('response_time', models.FloatField(help_text='Время обработки запроса в миллисекундах', verbose_name='Время ответа (мс)')),
                ('loaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки в БД')),
            ],
            options={
                'verbose_name': 'Запись лога веб-сервера',
                'verbose_name_plural': 'Записи логов веб-сервера',
                'indexes': [models.Index(fields=['timestamp'], name='etl_core_we_timesta_9e0629_idx'), models.Index(fields=['status_code'], name='etl_core_we_status__144fd2_idx')],
            },
        ),
    ]
